function z = matern52_ns_grad_l(g1,g2,g3,g4,r)
%MATERN52_NS_GRAD_L
%    Z = MATERN52_NS_GRAD_L(G1,G2,G3,G4,R)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    13-Feb-2020 09:55:44
%
% Tedious derivatives of non-stationary Matern 32 w.r.t. l
% Symbolic tool is the only healthy way to give it, thougn not efficient.
%
% Let 
%   g1 = g(σ(x))
%   g2 = g(σ(x'))
%   g3 = g(l(x))
%   g4 = g(l(x'))
%
% Code 
% syms g1 g2 g3 g4 r
% c(g1, g2, g3, g4, r) = g1*g2*g3^0.25*g4^0.25*(2/(g3+g4))^0.5*(1+r*sqrt(10/(g3+g4)) + 10/3*r^2/(g3+g4))*exp(-r*sqrt(10/(g3+g4)))
% z = simplify(diff(c, g4))
% f = matlabFunction(z, 'File', 'matern52_ns_grad_l')
% 
% Zheng Zhao (c) 2020
% zz@zabemon.com
%

t2 = g3+g4;
t3 = sqrt(1.0e+1);
t4 = 1.0./t2;
t5 = sqrt(t4);
z = (sqrt(2.0).*g1.*g2.*g3.^(1.0./4.0).*1.0./g4.^(3.0./4.0).*t5.^3.*exp(-r.*t3.*t5).*(g3.*3.0-g4.*3.0+r.^2.*1.0e+1+g3.*r.*t3.*t5.*3.0-g4.*r.*t3.*t5.*3.0+g4.*r.^3.*t3.*t5.^3.*2.0e+1))./1.2e+1;
