function z = matern32_ns_grad_ss(g1,g2,g3,g4,r)
%MATERN32_NS_GRAD_SS
%    Z = MATERN32_NS_GRAD_SS(G1,G2,G3,G4,R)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Feb-2020 20:04:58

t2 = sqrt(6.0);
t3 = g3+g4;
t4 = 1.0./t3;
t5 = sqrt(t4);
z = sqrt(2.0).*g2.*g3.^(1.0./4.0).*g4.^(1.0./4.0).*t5.*exp(-r.*t2.*t5).*(r.*t2.*t5+1.0).*2.0;
