function z = matern52_ns_grad_ss(g1,g2,g3,g4,r)
%MATERN52_NS_GRAD_SS
%    Z = MATERN52_NS_GRAD_SS(G1,G2,G3,G4,R)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    13-Feb-2020 10:03:35

t2 = g3+g4;
t3 = sqrt(1.0e+1);
t4 = 1.0./t2;
t5 = sqrt(t4);
t6 = r.*t3.*t5;
z = sqrt(2.0).*g2.*g3.^(1.0./4.0).*g4.^(1.0./4.0).*t5.*exp(-t6).*(t6+r.^2.*t4.*(1.0e+1./3.0)+1.0).*2.0;
