function z = matern32_ns_grad_l(g1,g2,g3,g4,r)
%MATERN32_NS_GRAD_L
%    Z = MATERN32_NS_GRAD_L(G1,G2,G3,G4,R)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Feb-2020 18:53:39
%
% Tedious derivatives of non-stationary Matern 32 w.r.t. l
% Symbolic tool is the only healthy way to give it, thougn not efficient.
%
% Let 
%   g1 = g(σ(x))
%   g2 = g(σ(x'))
%   g3 = g(l(x))
%   g4 = g(l(x'))
%
% Code 
% syms g1 g2 g3 g4 r
% c(g1, g2, g3, g4, r) = g1*g2*g3^0.25*g4^0.25*(2/(g3+g4))^0.5*(1+r*sqrt(6/(g3+g4)))*exp(-r*sqrt(6/(g3+g4)))
% z = simplify(diff(c, g4))
% f = matlabFunction(z, 'File', 'matern32_ns_grad_l')
% 
% Zheng Zhao (c) 2020
% zz@zabemon.com
%

t2 = g3+g4;
t3 = 1.0./t2;
t4 = sqrt(6.0);
t5 = g3.^2;
t6 = g4.^2;
t7 = t3.^(3.0./2.0);
t8 = t3.^(5.0./2.0);
z = sqrt(2.0).*g1.*g2.*g3.^(1.0./4.0).*1.0./g4.^(3.0./4.0).*1.0./t2.^3.*1.0./sqrt(t3).*exp(-r.*sqrt(t3).*t4).*(t5-t6+g4.*r.^2.*1.2e1-r.*t4.*t6.^2.*t8.*2.0+g3.*r.*t4.*t5.*t7+g3.*r.*t4.*t6.*t7.*3.0+g4.*r.*t4.*t5.*t7.*3.0+g4.*r.*t4.*t6.*t7-r.*t4.*t5.*t6.*t8.*6.0-g3.*g4.*r.*t4.*t5.*t8.*2.0-g3.*g4.*r.*t4.*t6.*t8.*6.0).*(1.0./4.0);
