function z = matern12_ns_grad_l(g1,g2,g3,g4,r)
%MATERN12_NS_GRAD_L
%    Z = MATERN12_NS_GRAD_L(G1,G2,G3,G4,R)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    11-Feb-2020 10:10:25
%
% Tedious derivatives of non-stationary Matern 12 w.r.t. l
% Symbolic tool is the only healthy way to give it, thougn not efficient.
%
% Let 
%   g1 = g(σ(x))
%   g2 = g(σ(x'))
%   g3 = g(l(x))
%   g4 = g(l(x'))
%
% Code 
% syms g1 g2 g3 g4 r
% c(g1, g2, g3, g4, r) = g1.*g2.*g3.^0.25.*g4.^0.25.*(2/(g3+g4)).^0.5.*exp(-r.*sqrt(2/(g3+g4)))
% z = simplify(diff(c, g4))
% f = matlabFunction(z, 'File', 'matern12_ns_grad_l')
% 
% Zheng Zhao (c) 2020
% zz@zabemon.com
%

t2 = g3+g4;
t3 = sqrt(2.0);
t4 = 1.0./t2;
t5 = 1.0./t4.^(5.0./2.0);
z = (g1.*g2.*g3.^(1.0./4.0).*1.0./g4.^(3.0./4.0).*t4.^4.*exp(-r.*t3.*sqrt(t4)).*(g4.^3.*r.*4.0+g3.*t3.*t5-g4.*t3.*t5+g3.*g4.^2.*r.*8.0+g3.^2.*g4.*r.*4.0))./4.0;
