function z = matern52_ns_grad_ll(g1,g3,r)
%MATERN52_NS_GRAD_LL
%    Z = MATERN52_NS_GRAD_LL(G1,G3,R)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    13-Feb-2020 10:01:16

t2 = sqrt(5.0);
z = g1.^2.*1.0./g3.^(5.0./2.0).*r.^3.*t2.*exp(-1.0./sqrt(g3).*r.*t2).*(5.0./4.0);
